name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if inspect-ai tasks are valid
      run: |
        python -c "
        from delve_bench import delve_bench, delve_bench_original
        print('Tasks imported successfully')
        task1 = delve_bench()
        task2 = delve_bench_original()
        print('Tasks created successfully')
        "
